/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cse110.lab6;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        QuickStart classUnderTest = new QuickStart();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
